### ISSUE TITLE
Request: Proper Documentation

### ISSUE THREAD

**Issue by Boobies** [MrMelon54/illegal-stack-fixer-fabric-1.16#2] opened 2022-02-02 11:05 UTC
It's not clear precisely what this mod does. Under which circumstances do vanilla stacks overflow? Which stack in particular? And why is there an emphasis on the fact that this is for servers? I would expect this to also be the case for client servers? This should probably be spelled out because it's not even clear to me whether any crashes can occur or why this is necessary.

**Comment by mrmelon54** [comment] 2022-02-02 11:57
This is mostly for servers preventing players having stacks bigger than the max stack size. This could be caused by glitches etc..). It was a specifically requested by a user on reddit.

Hopefully this clears this up. Feel free to close the issue or ask more questions.

**Comment by mrmelon54** [comment] 2022-02-02 12:04
Here is the original post

https://www.reddit.com/r/fabricmc/comments/ncxegt/looking_for_a_server_moddatapack_that_sets_the

**Closed as completed** 2022-02-17 17:09 UTC
